# -*- coding: utf-8 -*-
# Master-Thesis
# @ JKU IIC / ISP
# 2024
# Author: Simon Dorrer
# Description: Module for loading ngspice files into Python.
# Created: 02.04.2024
# Last Modified: 17.12.2024
# ============================================

# Imports
import numpy as np

# Function loadngspicecol
def loadngspicecol(textfile, colname):
    '''
    Import data into the workspace from a text file generated by Ngspice using
    the wrdata command assuming wr_vecnames and wr_singlescale have been set.  
    So, the first line of the file is assumed to contain unquoted variable
    names (e.g. v(vdac_out)). The column with the specified header name 
    is loaded into a numpy array.
    '''
    
    # Initialize an empty list to store data efficiently
    data = []

    # Read the text file
    with open(textfile, 'r') as file:
        # Read and split the header line
        header = file.readline().split()

        # Get column index (with error handling if column is not found)
        try:
            col_idx = header.index(colname)
        except ValueError:
            raise ValueError(f"Column '{colname}' not found in file '{textfile}'.")

        # Read remaining lines and extract the column data
        for line in file:
            data.append(float(line.split()[col_idx]))

    # Convert list to a NumPy array for better performance
    return np.array(data)
# ============================================

if __name__ == '__main__':
    print("This code will not be executed when this file is imported.")
# ============================================