name: Verify

on: [push]

jobs:
  verify-with-oss-cad-suite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get OSS CAD Suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        python-override: true

    - name: Verify Full System
      run: make all
      
  formal-with-oss-cad-suite:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tb:
          - full_adder_tb
          - n_adder_tb
          - alu_tb
          - counter_tb
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Get OSS CAD Suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        python-override: true

    - name: Formal Verify ${{ matrix.tb }}
      run: make formal TB=${{ matrix.tb }}