name: Verify

on: [push]

jobs:
  verify-with-oss-cad-suite:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get OSS CAD Suite
      uses: YosysHQ/setup-oss-cad-suite@v3
      with:
        python-override: true

    - name: Verify Full System
      run: make all