
name: Verify

on: [push]

jobs:
  verify-with-icarus:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Icarus
      run: |
        sudo apt install -y --no-install-recommends iverilog

    - name: Verify Full System
      run: make all